development:
  sessions:
    default:
      database: rails_crm_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: rails_crm_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

 # mongodb://heroku_app7056684:i49vdi86vsoidg0sn5unrqkf54@ds037387-a.mongolab.com:37387/heroku_app7056684
 
production:
  uri: ENV['MONGOLAB_URI']
      options:
        consistency: :strong
